(Initial) Контракт сервисов скраппера
Byte-Bosses/linktracker pull request #2
Opened 2024-04-10 17:54 UTC by arhostcode

#### Накидал контракт сервисов в scrapper для удобства разработки.
Предполагаемый вид ответа от InformationProvider
```json
{
  "uri": "https://example.com",
  "title": "Example Site",
  "events": [
    {
      "type": "push_event",
      "updateTime": "18:00 10.04.2024",
      "metaInfo": {
        "branch": "hello",
        "commmit": "world"
      }
    },
    {
      "type": "pull_request",
      "updateTime": "19:00 10.04.2024",
      "metaInfo": {
        "branch": "hello",
        "review": "arhostcode"
      }
    }
  ]
}
```

### Описание концепта metadata
В контексте information provider часто используется metaData или metaInformation, что я подразумеваю под этим?
В моём понимании это дополнительная информация идентифицирующая обновление.
Пример: для github provider это может быть дополнительная информация к event, которую хочу передать пользователю: ветка в которую произведён пуш, кто заревьювил ПР и тп.
В контексте stackoverflow это может быть информация о том сколько раз отвечено на вопрос, рейтинг вопроса и тп. Предполагается, что некоторая мета информация будет сохраняться в базе данных, для проверки следующих обновлений

2024-04-10 18:01 UTC, Nick-552 commented
Можешь привести пример мета информации которая нужна для проверки следующих обновлений? Не очень понимаю при каких условиях информации о времени последнего обновления будет недостаточно.

2024-04-10 18:23 UTC, arhostcode commented
Сайты по типу stackoverflow и тп не имеют возможности просмотра изменений в зависимости от времени и время обновления учитывается на всё подряд. Если мы хотим иметь возможность проверять что конкретно изменилось будем использовать мета информацию

2024-04-11 16:43 UTC, Nick-552 requested changes
Отлично! Осталось добавить dto, которые будут использованы для общения с модулем bot.

2024-04-11 16:43 UTC, Nick-552 commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/sender/UpdateSender.kt
> +    fun sendUpdate(update: LinkUpdateInformation)
Список чатов внутри этого метода будем получать?
Мб сделаем чтобы этот метод принимал какой-нибудь LinkUpdate где будет LinkUpdateInfo и список чатов?

2024-04-11 16:50 UTC, Nick-552 commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/sender/UpdateSender.kt
> +    fun sendUpdate(update: LinkUpdateInformation)
Я бы сделал так: в `sheduler` я беру линку, получаю по ней инфо из `InformationProvider`, получаю список чатов из `LinkService` формирую dto из информации и списка чатов и отправляю с помощью `UpdateSender`. Ну или же можно сделать метод в `LinkService`, который будет сразу получать и инфо и список чатов, но тогда нужно инжектить `InformationProviderRegistry` в него

2024-04-11 16:52 UTC, arhostcode commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/sender/UpdateSender.kt
> +    fun sendUpdate(update: LinkUpdateInformation)
Тогда реши как ты будешь, тогда сделаем так как удобнее будет

2024-04-11 18:03 UTC, Nick-552 commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/sender/UpdateSender.kt
> +    fun sendUpdate(update: LinkUpdateInformation)
Давай тогда первый вариант

2024-04-11 18:18 UTC, Nick-552 approved these changes

2024-04-11 19:33 UTC, Nick-552 commented
По поводу отсутствия DeleteLinkRequest, я так понял что это сделано чтобы не отклоняться от rest api спецификации (чтобы метод delete был без body). Я так понял что линка будет передаваться как path variable в виде linkId?

2024-04-11 19:34 UTC, arhostcode commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/dto/response/ListLinksResponse.kt
> +data class ListLinksResponse (
?

2024-04-11 19:35 UTC, Nick-552 commented
И с chatId тоже нужно определиться как передавать, через header или, как Дима делал по совету Сереги, через path variable

2024-04-11 19:36 UTC, arhostcode commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/dto/response/ListLinksResponse.kt
> +data class ListLinksResponse (
Предполагалось возвращать список как реальный список, а не объект содержащий только его
```yml
/links/{chat_id}:
    get:
      summary: Получить все отслеживаемые ссылки
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ссылки успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LinkResponse'

```

2024-04-11 19:37 UTC, Nick-552 commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/dto/response/ListLinksResponse.kt
> +data class ListLinksResponse (
Ну у нас вроде так было, или ты хочешь просто как лист передавать?

2024-04-11 19:37 UTC, arhostcode commented
Для этого я и запушил спецификацию, чтобы было понятно что и как

2024-04-11 19:40 UTC, arhostcode commented on scrapper/src/main/kotlin/ru/bytebosses/scrapper/dto/response/ListLinksResponse.kt
> +data class ListLinksResponse (
Ответил выше

2024-04-11 19:43 UTC, Nick-552 commented
А всё понял, сори, не заметил файл со спецификацией, в таком случае уберу класс и можно пушить в main, я думаю.

2024-04-11 19:46 UTC, merged